#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "controller.h"
#include "Frontend/workloadwindow.h"


/**
 * @brief MainWindow::MainWindow This is the standard constructor for my main window widget. It populates the empty scroll areas in the main with the four child widgets of the app.
 * @param parent This is the parent widget. It is not used.
 * @param schedule_panel This is the schedule panel widget. This is a graph generated by Qpainter.
 * @param workload_panel This is the workload panel. This panel allows a user to specify the properties of the periodic and aperiodic workloads by supplying input files or manually
 * inputting values.
 * @param analysis_panel This is the analysis panel. There are GUI elements in this widget that allow a user to specify what types of properties they want to observe
 * @param display_adjuster This panel is used for adjusting the display of the schedule_panel. It allows a user to zoom and specify time bounds to display.
 * @param controller This object controls all the widgets. It reads signals from widgets and routes the information to the other panels.
 */

MainWindow::MainWindow(QWidget* parent, QWidget* schedule_panel, WorkloadWindow* workload_panel, QWidget* analysis_panel, QWidget* display_adjuster, QObject* controller)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
{
    //Setup UI and intialize subwindows
    ui->setupUi(this);
    ui->scrollArea->setWidget(schedule_panel);
    ui->scrollArea_2->setWidget(workload_panel);
    ui->scrollArea_3->setWidget(analysis_panel);
    ui->scrollArea_4->setWidget(display_adjuster);

    //Create MainWindow refrences to child windows
    //Not necesary only done for ease of access
    this->schedule_panel = schedule_panel;
    this->workload_panel = workload_panel;
    this->analysis_panel = analysis_panel;
    this->display_adjuster = display_adjuster;
    this->controller = controller;

    //Map signals and slots
    connect_sigs();


}

MainWindow::~MainWindow()
{
    delete ui;
}

/**
 * @brief MainWindow::connect_sigs This function connects slots and signals that interact with the mainwindow widget.
 */
void MainWindow::connect_sigs(){

}



